import {
  Baby,
  Blocks,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Car,
  Check,
  Circle,
  ClipboardList,
  Clock,
  Compass,
  FlaskConical,
  GraduationCap,
  Hammer,
  Hand,
  Heart,
  House,
  Lightbulb,
  Map,
  Megaphone,
  MessageCircle,
  Monitor,
  Palette,
  Phone,
  Shield,
  Sparkles,
  Star,
  Sun,
  Tent,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

// Names editors can type in an Icons column (listed in the field hints in
// dotCMS, docs/build-education.py → ICONS).
const ICONS: Record<string, LucideIcon> = {
  baby: Baby,
  blocks: Blocks,
  book: BookOpen,
  briefcase: Briefcase,
  bus: Bus,
  calendar: Calendar,
  car: Car,
  check: Check,
  clipboard: ClipboardList,
  clock: Clock,
  compass: Compass,
  flask: FlaskConical,
  graduation: GraduationCap,
  hammer: Hammer,
  hands: Hand,
  heart: Heart,
  home: House,
  lightbulb: Lightbulb,
  map: Map,
  megaphone: Megaphone,
  message: MessageCircle,
  monitor: Monitor,
  palette: Palette,
  phone: Phone,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tent: Tent,
  users: Users,
  wallet: Wallet,
};

/** A line icon by name; unknown or empty names draw a plain circle. */
export function Icon({ name, className }: { name?: string; className?: string }) {
  const Glyph = ICONS[(name ?? "").toLowerCase()] ?? Circle;
  return <Glyph aria-hidden className={className} strokeWidth={1.5} />;
}
